<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.wildfly.security.examples</groupId>
    <artifactId>ssl-utils-simple-test</artifactId>
    <version>2.0.0.Alpha1-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <version.org.wildfly.security.wildfly-elytron>2.0.1.CR1-SNAPSHOT</version.org.wildfly.security.wildfly-elytron>
    </properties>

    <dependencies>
        <!-- interface SecurityRealm -->
        <dependency>
            <groupId>org.wildfly.security</groupId>
            <artifactId>wildfly-elytron-ssl</artifactId>
            <version>${version.org.wildfly.security.wildfly-elytron}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.security</groupId>
            <artifactId>wildfly-elytron-keystore</artifactId>
            <version>${version.org.wildfly.security.wildfly-elytron}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.bouncycastle/bctls-fips -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bctls-fips</artifactId>
            <version>1.0.14.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.bouncycastle/bc-fips -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bc-fips</artifactId>
            <version>1.0.2.3</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <executable>java</executable>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-two-way-ssl-stores</id>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <notimestamp>true</notimestamp>
                    <doclint>none</doclint>
                    <show>protected</show>
                    <sourceFileIncludes>
                        <include>org/wildfly/security/examples/CertificateGenerator.java</include>
                    </sourceFileIncludes>
                    <destDir>javadoc</destDir>
                </configuration>
                <executions>
                    <execution><!-- mvn javadoc:javadoc@full-javadoc -->
                        <id>full-javadoc</id>
                        <configuration>
                            <destDir>full-javadoc</destDir>
                            <show>private</show>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>9</source>
                    <target>9</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
